import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import ThemeProviderWrapper from "@/components/Settings/ThemeProviderWrapper";
import { getTranslations , getMessages } from "next-intl/server";
import {notFound} from 'next/navigation';
import { getLangDir }  from 'rtl-detect';


// Google Font
import { El_Messiri , DM_Sans } from "next/font/google";

// Styles
import "/public/assets/sass/animate.css";
import "./globals.css";
import "/public/assets/sass/globals.css"; 

// Components
import { Sidebar } from "@/components/shared/Sidebar";
/* import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import LoadingOverlay from "@/components/Settings/LoadingOverlay";
import LandingNavbar from "@/components/Landing/LandingNavbar";
import LandingFooter from "@/components/Landing/LandingFooter";
import TransitionEffect from "@/components/Settings/TransitionEffect"; */

// Font setup
const elMessiri = El_Messiri({
  subsets: ['arabic'],
  display: 'swap',
  variable: '--font-elMessiri',
});

const dmSans = DM_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-dmSans',
});

// Metadata
export async function generateMetadata(): Promise<Metadata> {

  const t = await getTranslations("Navbar"); 
  return {
    title: {
      default: "فينفيز | Finbiz",
      template: `%s | ${t("Metadata.title")}`
    },
    description: "Generated by Next.js",
    icons: {
      icon: '/assets/images/logo/favicon.ico', // remove `/public`, it's already public root
    },

  }
}

// Layout Component
export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const { locale } = await params;
  const direction = getLangDir(locale);


  // Ensure that the incoming `locale` is valid

  // Validate locale
  if (!["en", "ar"].includes(locale)) return notFound();

  const messages = await getMessages();

  
  return (
    <html
        lang={locale}
        dir={direction} // Sets the correct text direction (ltr or rtl)
        className={`${locale === 'ar' ? elMessiri.variable : dmSans.variable}`} // Apply the correct font variable
        suppressHydrationWarning
    >
                       
      <body className="bg-slate-50 dark:bg-slate-950 text-slate-900 dark:text-slate-100 transition-colors duration-300 font-sans text-left rtl:text-right">
  {/*     <LoadingOverlay /> */}
{/*    <TransitionEffect /> */}
      <ThemeProviderWrapper>

          <NextIntlClientProvider locale={locale} messages={messages}>
         {/*      <Navbar /> */}
                <div className="flex min-h-screen flex-col md:flex-row">
                  <Sidebar />
                  <main className="flex-1 w-full overflow-x-hidden min-h-screen relative p-4 lg:p-8 bg-[#f8fafc] dark:bg-slate-950 text-slate-900 dark:text-slate-50">{children}</main>
                </div>
     {/*         <LandingFooter /> */}
          </NextIntlClientProvider>
  
        </ThemeProviderWrapper>
   

      </body>
    </html>
  );
}
